/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DangNhapRouteImport } from './routes/dangNhap'
import { Route as DangKyRouteImport } from './routes/dangKy'
import { Route as IndexRouteImport } from './routes/index'

const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dangNhap',
  path: '/dangNhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dangKy',
  path: '/dangKy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dangKy': typeof DangKyRoute
  '/dangNhap': typeof DangNhapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dangKy': typeof DangKyRoute
  '/dangNhap': typeof DangNhapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dangKy': typeof DangKyRoute
  '/dangNhap': typeof DangNhapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dangKy' | '/dangNhap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dangKy' | '/dangNhap'
  id: '__root__' | '/' | '/dangKy' | '/dangNhap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dangNhap': {
      id: '/dangNhap'
      path: '/dangNhap'
      fullPath: '/dangNhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangKy': {
      id: '/dangKy'
      path: '/dangKy'
      fullPath: '/dangKy'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
